# Note: this is just temporary until we move to a docker.

apps:
  - script: /root/.cache/pypoetry/virtualenvs/backend-KZb_1nCG-py3.9/bin/gunicorn
    cwd: /root/former.fm/backend
    args: backend.api.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind=127.0.0.1:8888
    watch: false
    interpreter: /root/.cache/pypoetry/virtualenvs/backend-KZb_1nCG-py3.9/bin/python
    name: "JoshAPI"

  - script: /root/.cache/pypoetry/virtualenvs/backend-KZb_1nCG-py3.9/bin/celery
    cwd: /root/former.fm/backend
    args: -A backend.background.configuration.celery_configuration.background worker -E
    interpreter: /root/.cache/pypoetry/virtualenvs/backend-KZb_1nCG-py3.9/bin/python
    name: "JoshCelery"
    watch: false

  